### PR TITLE
Add flatten extensions on `EventLoop`

### PR DESCRIPTION
**Pull request by Mordil**
Brings an implementation of [`flatten`](https://github.com/vapor/core/blob/master/Sources/Async/Future%2BFlatten.swift#L42) from Vapor/Core

Example usage:

```swift
let elg = MultiThreadedEventLoopGroup(threadCount: 1)
let future = elg.next().flatten(...).wait()
```

### CODE REVIEW

**Comment by Mordil** [comment]
@calebkleveter This PR can be closed - I thought I had done it awhile back. These methods are now available from SwiftNIO itself as [`whenAllSucceed`](https://github.com/apple/swift-nio/blob/master/Sources/NIO/EventLoopFuture.swift#L1006) and [`whenAllComplete`](https://github.com/apple/swift-nio/blob/master/Sources/NIO/EventLoopFuture.swift#L1048)

**Comment by calebkleveter** [comment]
@Mordil Ha! Thanks for saving me the trouble 😄.

**Comment by Mordil** [comment]
I mean, we probably can keep these extensions on Collection and EventLoop - but perhaps we want to just change the implementation.

**Comment by tanner0101** [comment]
I think we should keep the extensions, they are pretty useful. At the very least, we should offer them as deprecated methods given how commonly used they are.

**Comment by calebkleveter** [comment]
@tanner0101 Sounds good! @MrLotU Mind reviewing this again?

**Comment by penny-coin** [comment]
Hey @Mordil, you just merged a pull request, have a coin! 

You now have 46 coins.

**Pull request merged**
